import { useEffect, useState } from "react";

const API="https://smart-health-portal-backend-production.up.railway.app";
function user(){ try{return JSON.parse(localStorage.getItem("user"));}catch{return null;} }
export default function BMI(){
 const [height,setHeight]=useState(""); const [weight,setWeight]=useState(""); const [result,setResult]=useState(null); const [history,setHistory]=useState([]); const [message,setMessage]=useState("");
 const u=user();
 const load=async()=>{if(!u)return; const r=await fetch(`${API}/api/bmi/${u.id}`); const d=await r.json(); if(d.success)setHistory(d.records);};
 useEffect(()=>{load();},[]);
 const calculate=async e=>{e.preventDefault(); setMessage(""); const h=Number(height),w=Number(weight); if(!h||!w||h<=0||w<=0){setMessage("Please enter valid height and weight.");return;} const r=await fetch(`${API}/api/bmi`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:u.id,height:h,weight:w})}); const d=await r.json(); if(d.success){setResult(d);setMessage("BMI calculated and saved to your history.");load();}else setMessage(d.message||"Could not save BMI.");};
 return <div className="min-h-screen bg-blue-50 py-12 px-6"><div className="max-w-4xl mx-auto"><div className="text-center mb-10"><span className="text-blue-600 font-semibold">HEALTHCARE TOOL</span><h1 className="text-4xl font-bold text-gray-800 mt-2">BMI Tracker</h1><p className="text-gray-600 mt-3">Calculate your BMI and keep a personal history.</p></div><div className="bg-white rounded-2xl shadow-lg p-8"><form onSubmit={calculate}><div className="grid md:grid-cols-2 gap-6"><div><label className="block font-semibold mb-2">Height (cm)</label><input type="number" value={height} onChange={e=>setHeight(e.target.value)} className="w-full border rounded-lg px-4 py-3" placeholder="170"/></div><div><label className="block font-semibold mb-2">Weight (kg)</label><input type="number" value={weight} onChange={e=>setWeight(e.target.value)} className="w-full border rounded-lg px-4 py-3" placeholder="65"/></div></div><button className="mt-8 w-full bg-blue-600 text-white font-semibold py-3 rounded-lg">Calculate & Save BMI</button></form>{message&&<p className="text-center mt-4 text-blue-700">{message}</p>}{result&&<div className="mt-7 text-center bg-blue-50 rounded-xl p-6"><p className="text-gray-600">Your BMI</p><p className="text-5xl font-bold text-blue-600 mt-2">{result.bmi}</p><p className="text-xl font-semibold mt-2">{result.category}</p></div>}</div><div className="bg-white rounded-2xl shadow-lg p-8 mt-8"><h2 className="text-2xl font-bold mb-5">BMI History</h2>{history.length?<div className="space-y-3">{history.map(x=><div key={x.id} className="border rounded-xl p-4 flex justify-between"><span>{new Date(x.created_at).toLocaleString()}</span><span className="font-semibold">{x.bmi} — {x.category}</span></div>)}</div>:<p className="text-gray-500">No BMI records yet.</p>}<p className="text-sm text-gray-500 mt-5">BMI is a general screening measure and does not replace professional medical advice.</p></div></div></div>;
}
