import {useEffect,useState} from "react";
const API="http://localhost:5000";
const getUser=()=>{try{return JSON.parse(localStorage.getItem("user"));}catch{return null;}};
function keyToBytes(base64){const p="=".repeat((4-base64.length%4)%4),b=(base64+p).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
export default function PillReminder(){const u=getUser();const [medicine,setMedicine]=useState("");const [time,setTime]=useState("");const [dosage,setDosage]=useState("");const [reminders,setReminders]=useState([]);const [notice,setNotice]=useState("");
 const load=async()=>{const r=await fetch(`${API}/api/pill-reminders/${u.id}`);const d=await r.json();if(d.success)setReminders(d.reminders);}; useEffect(()=>{load();},[]);
 const enableNotifications=async()=>{try{if(!(window.Notification&&navigator.serviceWorker&&window.PushManager)){alert("Your browser does not support push notifications.");return;}const permission=await Notification.requestPermission();if(permission!=="granted"){alert("Notification permission was not granted.");return;}const reg=await navigator.serviceWorker.register("/service-worker.js");const kr=await fetch(`${API}/api/push/public-key`);const kd=await kr.json();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyToBytes(kd.publicKey)});const sr=await fetch(`${API}/api/push/subscribe`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:u.id,subscription:sub})});const sd=await sr.json();if(!sr.ok)throw Error(sd.message);setNotice("🔔 Browser notifications are enabled.");}catch(e){console.error(e);alert("Could not enable notifications. Make sure the backend is running and .env is configured.");}};
 const add=async e=>{e.preventDefault();if(!medicine||!time){alert("Enter medicine and time.");return;}const r=await fetch(`${API}/api/pill-reminders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:u.id,medicine_name:medicine,dosage,reminder_time:time})});const d=await r.json();if(d.success){setMedicine("");setTime("");setDosage("");setNotice("Reminder saved in MySQL.");load();}else alert(d.message);};
 const del=async id=>{await fetch(`${API}/api/pill-reminders/${id}`,{method:"DELETE"});load();};
 return <div className="min-h-screen bg-blue-50 py-12 px-6"><div className="max-w-4xl mx-auto"><div className="text-center mb-10"><div className="text-6xl">💊</div><h1 className="text-4xl font-bold text-blue-700 mt-3">Pill Reminder</h1><p className="text-gray-600 mt-3">Save reminders to MySQL and receive browser notifications.</p></div><div className="bg-white rounded-2xl shadow-lg p-8 mb-8"><form onSubmit={add}><div className="grid md:grid-cols-3 gap-5"><div><label className="block font-semibold mb-2">Medicine</label><input value={medicine} onChange={e=>setMedicine(e.target.value)} className="w-full border rounded-lg px-4 py-3" placeholder="Vitamin C"/></div><div><label className="block font-semibold mb-2">Dosage</label><input value={dosage} onChange={e=>setDosage(e.target.value)} className="w-full border rounded-lg px-4 py-3" placeholder="1 tablet"/></div><div><label className="block font-semibold mb-2">Time</label><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="w-full border rounded-lg px-4 py-3"/></div></div><button className="mt-6 w-full bg-blue-600 text-white py-3 rounded-lg font-semibold">Save Reminder</button></form></div><div className="bg-white rounded-2xl shadow-lg p-6 mb-8 flex items-center justify-between gap-4"><div><h3 className="font-bold">Real Browser Notifications</h3><p className="text-sm text-gray-500">Enable once to allow scheduled push notifications.</p>{notice&&<p className="text-green-600 mt-2">{notice}</p>}</div><button onClick={enableNotifications} className="bg-green-600 text-white px-5 py-3 rounded-lg font-semibold">Enable</button></div><div className="bg-white rounded-2xl shadow-lg p-8"><h2 className="text-2xl font-bold mb-5">My Reminders</h2>{reminders.length?reminders.map(r=><div key={r.id} className="border rounded-xl p-5 flex justify-between items-center mb-3"><div><b>💊 {r.medicine_name}</b><p className="text-blue-600">⏰ {String(r.reminder_time).slice(0,5)} {r.dosage&&`• ${r.dosage}`}</p></div><button onClick={()=>del(r.id)} className="bg-red-500 text-white px-4 py-2 rounded-lg">Delete</button></div>):<p className="text-gray-500">No reminders yet.</p>}</div></div></div>}
